#PELT I18N (Internationalization)
#Created December 4, 2013 at 15:30

import config
import os.path, pickle, re

def setlang(lang):
	global msgs
	langdir = os.path.join(config.langdir, lang)
	msgs = {}
	for l in os.listdir(langdir):
		langfile = os.path.join(langdir, l)
		if not "Icon" in l:
			if not "desktop.ini" in l:
				if not ".DS_Store" in l: #These three lines prevent invisible files generated by Google Drive or Macs from causing problems
					with open(langfile, 'rb') as handle: msgs.update(pickle.load(handle))
	config.lang = lang
	config.saveopt()

def language():
	wait=True
	wait2=True
	while wait:
		while wait2:
			choice = getInput.choice('Language/Idioma', ['English','Espanol (Archivo del Idioma no Esta Presente)','Francais (Fichier de Langue pas present)', 'Quit'])
			if choice == 'English':
				setlang("en")
				wait2 = False
			elif choice == '': quit('', nosave=True)
			else: output("Invalid option/Opcion incorrecto/L'option invalide", dict=False)
		else: output("Language File Version Incompatible/Version del Archivo del Idioma Incompatible/Version de L'archive du Language Incompatible", dict=False)
	
def m(key, r=0, modifier='normal', color=False):
	global msgs
	if r == 1: print "You should fix this message, it has m('"+key+"', r=1).  Remove the r=1"
	msg = msgs[key]
	if not color: re.sub(msg, "\[[^\]]\]", "")
	return msg
	#if modifier == 'caps': msg = msgs[key].upper()
	#elif modifier == 'title': msg = msgs[key].title()
	#elif modifier == 'lower': msg = msgs[key].lower()
	#return msg

setlang('en')