msgs = {'title':'Fur',
'author':'Creado por Dark Tailed',
'version':'Version %s',
'title2':'Fur - Version %s',
'save1':'Archivo %s',
'save2':'Archivo %s: %s',
'save3':'Guardar al Archivo',
'save4':'Cargar al Archivo',
'savewarning':'ATTENCION: Archivo en uso de %s %s el/la %s.  Bien para sobrescribir?',
'saveerror':'Archivo no valido',
'colorerror':'Color no valido',
'inputerror':'Entrada no valida',
'nofriendnameerror':"No te endrada el nombre de tu amigo!  Recuerda, %s esta un(a) %s.",
'mailto1':'mailto:dark.tailed.wolf@gmail.com?subject=I%20just%20played%20your%20game%20Fur!&body=I%20rate%20Fur%20(out%20of%205):%20',
'mailto2':'Gracias a jugar a Fur!  Por favor enviar sus comentarios pulsando en mi.',
'next':'Siguente Pagina',
'yes':'Si',
'no':'No',
'quit':'Quitar',
'back':'Atras',
'cancel':'Cancelar',
'ok':'Ok',
'med':'Medio',
'fast':'Rapido',
'slow':'Lento',
'boy':'Niño',
'girl':'Niña',
'he':'el',
'she':'ella',
'her':'ella',
'him':'el',
'his':'ello',
'meyou':"tu y yo",
'you':"tu",
'wolf':"Lobo",
'cat':"Gato",
'dragon':"Dragon",
'bear':"Oso",
'fox':"Zorro",
'mouse':"Raton",
'bird':"Pajaro",
'otter':"Nutria",
'broken1':'Hay algunas partes del juego que no funciona del momento.  Las partes se corregirán en breve. Para cerrar estas alertas, hace clic en el "%s".',
'broken2':'No Funciona',
'broken3':"No funciona!",
'broken4':"La siguiente parte esta todavia en desarrollo.  Cargue en un archivo del Beta Tester ahorra para desbloquear la siguiente parte.",
'start':'Comienze Juego',
'load':'Cargar al Archivo (No Funciona)',
'options':'Opciones',
'scroll':'Velocidad de Desplazamiento (%s)',
'annoy':'Modo de Molestia (No Funciona)',
'beta':'Modo de Beta Tester',
'annoyon':"Modo de molestia esta activado.",
'betaon':"Modo de beta tester esta activado.",
'annoyoff':"Modo de molestia esta desactivado.",
'betaoff':"Modo de beta tester esta desactivado.",
'quitmsg':"Sali del juego en la demanda del usuario.",
'setup1':'Estas un niño o una niña?',
'setup2':'Tu nombre es?',
'setup3':'%s...y tu apellido?', #continue translating VVV
'setup4':'%s %s...Bueno.  Ahora puede entrar por las puertas y se encuentra en "Fur"...cerrar los ojos y contar hasta 3, y despues abra los ojos...', 
'setup5':"Debisa abrir tus ojos ahorra.  Bueno.  Esto se completa el primero parte de tu <rebirth>.",
'setup6':"The final part of your rebirth is to know what animal you would be if you couldn't be human anymore.",
'setup7':"hace un click en un animal",
'setup8':"You have chosen a %s.  Excellent...This concludes the second part of your rebirth.  You will enter Quilar as a half-%s...",
'p1m1':'???: ...', #continue translating ^^^
'p1m2':'???: ...Oye...',
'p1m3':'???: ...Despierta...',
'p1m4':'???: ...Oye, %s perezoso!',
'p1m5':'???: Despierta!',
'p1m6':'Lentamente abre tus ojos.  Un(a) %s about your age is trying to shake you awake.  You notice something strange about the %s, but your eyes are still blurred from waking up.',
'p1m7':"???: You're awake!  I've been shaking you for over an hour or so!",
'p1m8':"Your eyes focus and you figure out why the %s looked so strange.  %s was fox-like, with fur covering %s entire body, and a big tail sticking out behind %s.",
'p1m9':"Your eyes widen and you quickly push yourself back into the wall.  You then raise your arms ready to attack.",
'p1m10':'You: Who are you?',
'p1m11':"???: Me?  My name is...",
'setup9':'Enter the name of your friend, remember, %s is a %s.',
'p1m12':"%s.  What's yours?",
'p1m13':"You lower your fists.",
'p1m14':"You: ...I'm %s.",
'p1m15':"%s: %s...it's a funny name for a %s like %s!",
'p1m16':"You: What?",
'p1m17':"You then look down at yourself.  %s",
'foxdesc':"You also look just like a fox, with a tail and everything.",
'dragondesc':"You have scales and the tail of a dragon.  In your throat you feel a hot presence.",
'p1m18':"They are in a similar state to those of the %s's.  %s",
'birddesc':"However you have feathers down your arms like wings and a retrice.  You feel your face and find a bird's beak for your mouth.",
'wolfdesc':"However you look more like a wolf with a wolf's tail.  You feel your face and find a big snout.",
'catdesc':"However your hands have very sharp claws and you look more like a cat.",
'beardesc':"However you have big hands, big feet, and a short, stubby tail.  You have brown fur just like a bear.",
'mousedesc':"However you have small hands, a skinny tail, and big ears, just like a mouse.",
'otterdesc':"However your hands look more like an otter's.  You feel your face and find wet quills.  Behind you is a long tail.",
'p1m19':"You start to panic inside.  You think 'what is going on?'",
'p1m20':"%s: ...What?",
'p1m21':"You tell yourself to calm down so you can figure out why you're half-%s.",
'p1m22':"You: I'm a human though...",
'p1m23':"You accidentally said the last part out loud.  You meant only to think it.",
'p1m24':"%s: WHAT!  You can't be, you've got every aspect of a %s anthro...(%s comes close to you and sniffs you, then pulls back)...and you smell just like one too.",
'p1m25':"You: Yeah, thanks.",
'p1m26':"%s: I didn't mean it like that!",
'p1m27':"You: I don't know what's going on, but we're going to have to find out.  Where are we?",
'p1title':'PART 1: Prologue',
'gamestart':"You are in a room.",
'gameaction':"What will you do?",
'gameinputerror':"I didn't understand what you typed.",
'helpquit':'quit - Saves and quits the game.',
'quitmsg':"Quit on user's demand.",
'quitcmd':'quit',
'savecmd':'save',
'helpsave':'save - Saves the game',
'loadcmd':'load',
'helpload':'load - Loads the game from a save file (dangerous)',
'helpcmd':'help',
'helphelp':'help - Displays this message',
'examinecmd':'examine',
'helpexamine':'examine [item] - shows description of item',
'eatcmd':'eat',
'helpeat':'eat [item] - If item is food, will eat item',
'drinkcmd':'drink',
'helpdrink':'drink [item] - if item is a drink, will drink item',
'takecmd':'take',
'helptake':'take [item] - if item is movable, will take item',
'gocmd':'go',
'helpgo':'go [direction] - Go through the door in the defined direction',
'doormissing':"There is no door in that direction.",
'doorlocked':"You try to open the door but the handle won't budge.",
'directionerror':"That's not a proper direction.",
'itemerror':"I don't see any %s here.",
'cmderror':"I don't know how to do that.",
'with':'with',
'using':'using',
'usingerror':"What do you want to %s the %s with?",
'itemnormal':"This %s doesn't seem to be unusual.",
'foodpoisoned':"That %s was covered in fatal poison.  You are now dead.",
'foodpoisonedmsg':'User ate a poisoned %s',
'foodeaten':"That %s was very tasty!",
'drinkpoisoned':"That %s had a fatal poison inside.  You are now dead.",
'drinkpoisonedmdg':'User drank poison from a %s',
'playerdesc':'%s %s the %s %s, carrying %s, at %s, Level %s.  Can use the attacks %s',
'attackerror':'Not a valid attack.',
'itemhere':"There is a %s here",
'doorhere':"There is a door to the %s",
'doordesc':"A door to the %s that leads to the %s.",
'attack1':'Punch',
'attack1desc':'A simple punch',
'type1':'Normal',
'lang':'Language',
'iosask':'Are you on an iPhone or iPad?  This is important for gameplay.',
'iosquit':'User did not choose iPhone or iPad.'
}

import pickle

with open('spanish.lang', 'wb') as handle: pickle.dump(msgs, handle)