msgs = {'title':'Fur',
'author':'Made by Dark Tailed',
'version':'Version ADDON',
'title2':'Fur - Version ADDON',
'save1':'Save ADDON',
'save2':'Save ADDON: ADDON',
'save3':'Save to File',
'save4':'Load File',
'savewarning':'WARNING: File belongs to ADDON ADDON the ADDON.  Okay to overwrite?',
'saveerror':'Not a valid save file.',
'colorerror':'Color input was invalid.',
'inputerror':'Invalid Input',
'mailto1':'mailto:dark.tailed.wolf@gmail.com?subject=I%20just%20played%20your%20game%20Fur!&body=I%20rate%20Fur%20(out%20of%205):%20',
'mailto2':'Thanks for playing fur!  Please send feedback by tapping on me.',
'next':'Next Page',
'yes':'Yes',
'no':'No',
'quit':'Quit',
'back':'Back',
'cancel':'Cancel',
'ok':'Ok',
'med':'Medium',
'fast':'Fast',
'slow':'Slow',
'boy':'Boy',
'girl':'Girl',
'he':'He',
'she':'She',
'meyou':"me and you",
'you':"you",
'wolf':"Wolf",
'cat':"Cat",
'dragon':"Dragon",
'bear':"Bear",
'fox':"Fox",
'mouse':"Mouse",
'bird':"Bird",
'otter':"Otter",
'broken1':'There are some parts of the game that are broken at the moment.  Those parts will be fixed soon.  To close these popup alerts, press "ADDON"',
'broken2':'Broken ATM',
'broken3':"It's broken at the moment!",
'broken4':"Next part is still in development.  Please load in a developer save to unlock the next part.",
'start':'Start Game',
'load':'Load Game (ADDON)',
'options':'Options',
'scroll':'Scroll Speed (ADDON)',
'annoy':'Annoyance Mode (ADDON)',
'beta':'Beta Tester Mode',
'annoyon':"Annoyance mode now active.",
'betaon':"Beta tester mode now active.",
'annoyoff':"Annoyance mode revoked.",
'betaoff':"Beta tester mode revoked.",
'quitmsg':"Quit on user's demand.",
'setup1':'Are you a boy or a girl?',
'setup2':'Your name is?',
'setup3':'ADDON...and your last?',
'setup4':'ADDON ADDON...Good.  Now you may enter the gates and find yourself in "Fur"...close your eyes and count to 3, then open your eyes...',
'setup5':"You should've opened your eyes by now.  Good.  You have finished the first part of your rebirth.",
'setup6':"The final part of your rebirth is to know what animal you would be if you couldn't be human anymore.",
'setup7':"Choose an animal",
'setup8':"You have chosen a ADDON.  Excellent...This concludes the second part of your rebirth.  You will enter Quilar as a half-ADDON...",
'p1m1':'???: ...',
'p1m2':'???: ...Hey...',
'p1m3':'???: ...Wake up...',
'p1m4':'???: ...Hey, you lazy ADDON!',
'p1m5':'???: Wake up!',
'p1m6':'You slowly open your eyes.  A young ADDON about your age is trying to shake you awake.  You notice something strange about the ADDON, but your eyes are still blurred from waking up.',
'p1m7':"???: You're awake!  I've been shaking you for over an hour or so!",
'p1m8':"You're eyes focus and you figure out why the ADDON looked so strange.  ADDON was fox-like, with fur covering ADDON entire body, and a big tail sticking out behind ADDON.",
'p1m9':"Your eyes widen and you quickly push yourself back into the wall.  You then raise your arms ready to attack.",
'p1m10':'You: Who are you?',
'p1m11':"???: Me?  My name is...",
'setup9':'Enter the name of your friend, remember, ADDON is a ADDON.',
'p1m12':"ADDON.  What's yours?",
'p1m13':"You lower your fists.",
'p1m14':"You: ...I'm ADDON.",
'p1m15':"ADDON: ADDON...it's a funny name for a ADDON like ADDON!",
'p1m16':"You: What?",
'p1m17':"You then look down at yourself.  ADDON",
'foxdesc':"You also look just like a fox, with a tail and everything.",
'dragondesc':"You have scales and the tail of a dragon instead of the fur like a fox.",
'p1m18':"They are in a similar state to those of the ADDON's.  ADDON",
'birddesc':"However you have feathers down your arms like wings and a retrice.  You feel your face and find a bird's beak for your mouth.",
'wolfdesc':"However you look more like a wolf with a wolf's tail.  You feel your face and find a big snout.",
'catdesc':"However your hands have very sharp claws and you look more like a cat.",
'beardesc':"However you have big hands, big feet, and a short, stubby tail.  You have brown fur just like a bear.",
'mousedesc':"However you have small hands, a skinny tail, and big ears, just like a mouse.",
'otterdesc':"However your hands look more like an otter's.  You feel your face and find wet quills.  Behind you is a long tail.",
'p1m19':"You start to panic inside.  You think 'what is going on?'",
'p1m20':"ADDON: ...What?",
'p1m21':"You tell yourself to calm down so you can figure out why you're half-ADDON.",
'p1m22':"You: I'm a human though...",
'p1m23':"You accidentally said the last part out loud.  You meant only to think it.",
'p1m24':"ADDON: WHAT!  You can't be, you've got every aspect of a ADDON anthro...(ADDON comes close to you and sniffs you, then pulls back)...and you smell just like one too.",
'p1m25':"You: Yeah, thanks.",
'p1m26':"ADDON: I didn't mean it like that!",
'p1m27':"You: I don't know what's going on, but we're going to have to find out.  Where are we?",
'p1title':'PART 1: Prologue',
'gamestart':"You are in a room.",
'gameaction':"What will you do?",
'gameinputerror':"I didn't understand what you typed.",
'quit':'quit',
'helpquit':'quit - Saves and quits the game.',
'quitmsg':"Quit on user's demand.",
'save':'save',
'helpsave':'save - Saves the game',
'load':'load',
'helpload':'load - Loads the game from a save file (dangerous)',
'help':'help',
'helphelp':'help - Displays this message',
'examine':'examine',
'helpexamine':'examine [item] - shows description of item',
'eat':'eat',
'helpeat':'eat [item] - If item is food, will eat item',
'drink':'drink',
'helpdrink':'drink [item] - if item is a drink, will drink item',
'take':'take',
'helptake':'take [item] - if item is movable, will take item',
'go':'go',
'helpgo':'go [direction] - Go through the door in the defined direction',
'doormissing':"There is no door in that direction.",
'doorlocked':"You try to open the door but the handle won't budge.",
'directionerror':"That's not a proper direction.",
'itemerror':"I don't see any ADDON here.",
'cmderror':"I don't know how to do that.",
'with':'with',
'using':'using',
'usingerror':"What do you want to ADDON the ADDON with?",
'itemnormal':"This ADDON doesn't seem to be unusual.",
'foodpoisoned':"That ADDON was covered in fatal poison.  You are now dead.",
'foodpoisonedmsg':'User ate a poisoned ADDON',
'foodeaten':"That ADDON was very tasty!",
'drinkpoisoned':"That ADDON had a fatal poison inside.  You are now dead.",
'drinkpoisonedmdg':'User drank poison from a ADDON',
'playerdesc':'ADDON ADDON the ADDON ADDON, carrying ADDON, at ADDON, Level ADDON.  Can use the attacks ADDON',
'attackerror':'Not a valid attack.',
'itemhere':"There is a ADDON here",
'doorhere':"There is a door to the ADDON",
'doordesc':"A door to the ADDON that leads to the ADDON.",
'attack1':'Punch',
'attack1desc':'A simple punch',
'type1':'Normal',
'lang':'Language',
'iosask':'Are you on an iPhone or iPad?  This is important for gameplay.',
'iosaskmsg':'User did not choose iPhone or iPad.'
}

import pickle

with open('english.lang', 'wb') as handle: pickle.dump(msgs, handle)
