msgs = {'title':'Fur',
'author':'Made by Dark Tailed',
'version':'Version %s',
'title2':'Fur - Version %s',
'save1':'Save %s',
'save2':'Save %s: %s',
'save3':'Save to File',
'save4':'Load File',
'savewarning':'WARNING: File belongs to %s %s the %s.  Okay to overwrite?',
'saveerror':'Not a valid save file.',
'colorerror':'Color input was invalid.',
'inputerror':'Invalid Input',
'nofriendnameerror':"You didn't type your friend's name!  Remember, %s is a %s.",
'mailto1':'mailto:dark.tailed.wolf@gmail.com?subject=I%20just%20played%20your%20game%20Fur!&body=I%20rate%20Fur%20(out%20of%205):%20',
'mailto2':'Thanks for playing fur!  Please send feedback by tapping on me.',
'next':'Next Page',
'yes':'Yes',
'no':'No',
'quit':'Quit',
'back':'Back',
'cancel':'Cancel',
'ok':'Ok',
'med':'Medium',
'fast':'Fast',
'slow':'Slow',
'boy':'Boy',
'girl':'Girl',
'he':'he',
'she':'she',
'her':'her',
'him':'him',
'his':'his',
'meyou':"me and you",
'you':"you",
'wolf':"Wolf",
'cat':"Cat",
'dragon':"Dragon",
'bear':"Bear",
'fox':"Fox",
'mouse':"Mouse",
'bird':"Bird",
'otter':"Otter",
'broken1':'There are some parts of the game that are broken at the moment.  Those parts will be fixed soon.  To close these popup alerts, press "%s"',
'broken2':'Broken ATM',
'broken3':"It's broken at the moment!",
'broken4':"Next part is still in development.  Please load in a developer save to unlock the next part.",
'start':'Start Game',
'load':'Load Game (Broken ATM)',
'options':'Options',
'scroll':'Scroll Speed (%s)',
'annoy':'Annoyance Mode (Broken ATM)',
'beta':'Beta Tester Mode',
'annoyon':"Annoyance mode now active.",
'betaon':"Beta tester mode now active.",
'annoyoff':"Annoyance mode revoked.",
'betaoff':"Beta tester mode revoked.",
'quitmsg':"Quit on user's demand.",
'setup1':'Are you a boy or a girl?',
'setup2':'Your name is?',
'setup3':'%s...and your last?',
'setup4':'%s %s...Good.  Now you may enter the gates and find yourself in "Fur"...close your eyes and count to 3, then open your eyes...',
'setup5':"You should've opened your eyes by now.  Good.  You have finished the first part of your rebirth.",
'setup6':"The final part of your rebirth is to know what animal you would be if you couldn't be human anymore.",
'setup7':"Choose an animal",
'setup8':"You have chosen a %s.  Excellent...This concludes the second part of your rebirth.  You will enter Quilar as a half-%s...",
'p1m1':'???: ...',
'p1m2':'???: ...Hey...',
'p1m3':'???: ...Wake up...',
'p1m4':'???: ...Hey, you lazy %s!',
'p1m5':'???: Wake up!',
'p1m6':'You slowly open your eyes.  A young %s about your age is trying to shake you awake.  You notice something strange about the %s, but your eyes are still blurred from waking up.',
'p1m7':"???: You're awake!  I've been shaking you for over an hour or so!",
'p1m8':"You're eyes focus and you figure out why the %s looked so strange.  %s was fox-like, with fur covering %s entire body, and a big tail sticking out behind %s.",
'p1m9':"Your eyes widen and you quickly push yourself back into the wall.  You then raise your arms ready to attack.",
'p1m10':'You: Who are you?',
'p1m11':"???: Me?  My name is...",
'setup9':'Enter the name of your friend, remember, %s is a %s.',
'p1m12':"%s.  What's yours?",
'p1m13':"You lower your fists.",
'p1m14':"You: ...I'm %s.",
'p1m15':"%s: %s...it's a funny name for a %s like %s!",
'p1m16':"You: What?",
'p1m17':"You then look down at yourself.  %s",
'foxdesc':"You also look just like a fox, with a tail and everything.",
'dragondesc':"You have scales and the tail of a dragon.  In your throat you feel a hot presence.",
'p1m18':"They are in a similar state to those of the %s's.  %s",
'birddesc':"However you have feathers down your arms like wings and a retrice.  You feel your face and find a bird's beak for your mouth.",
'wolfdesc':"However you look more like a wolf with a wolf's tail.  You feel your face and find a big snout.",
'catdesc':"However your hands have very sharp claws and you look more like a cat.",
'beardesc':"However you have big hands, big feet, and a short, stubby tail.  You have brown fur just like a bear.",
'mousedesc':"However you have small hands, a skinny tail, and big ears, just like a mouse.",
'otterdesc':"However your hands look more like an otter's.  You feel your face and find wet quills.  Behind you is a long tail.",
'p1m19':"You start to panic inside.  You think 'what is going on?'",
'p1m20':"%s: ...What?",
'p1m21':"You tell yourself to calm down so you can figure out why you're half-%s.",
'p1m22':"You: I'm a human though...",
'p1m23':"You accidentally said the last part out loud.  You meant only to think it.",
'p1m24':"%s: WHAT!  You can't be, you've got every aspect of a %s anthro...(%s comes close to you and sniffs you, then pulls back)...and you smell just like one too.",
'p1m25':"You: Yeah, thanks.",
'p1m26':"%s: I didn't mean it like that!",
'p1m27':"You: I don't know what's going on, but we're going to have to find out.  Where are we?",
'p1title':'PART 1: Prologue',
'gamestart':"You are in a room.",
'gameaction':"What will you do?",
'gameinputerror':"I didn't understand what you typed.",
'helpquit':'quit - Saves and quits the game.',
'quitmsg':"Quit on user's demand.",
'quitcmd':'quit',
'savecmd':'save',
'helpsave':'save - Saves the game',
'loadcmd':'load',
'helpload':'load - Loads the game from a save file (dangerous)',
'helpcmd':'help',
'helphelp':'help - Displays this message',
'examinecmd':'examine',
'helpexamine':'examine [item] - shows description of item',
'eatcmd':'eat',
'helpeat':'eat [item] - If item is food, will eat item',
'drinkcmd':'drink',
'helpdrink':'drink [item] - if item is a drink, will drink item',
'takecmd':'take',
'helptake':'take [item] - if item is movable, will take item',
'gocmd':'go',
'helpgo':'go [direction] - Go through the door in the defined direction',
'doormissing':"There is no door in that direction.",
'doorlocked':"You try to open the door but the handle won't budge.",
'directionerror':"That's not a proper direction.",
'itemerror':"I don't see any %s here.",
'cmderror':"I don't know how to do that.",
'with':'with',
'using':'using',
'usingerror':"What do you want to %s the %s with?",
'itemnormal':"This %s doesn't seem to be unusual.",
'foodpoisoned':"That %s was covered in fatal poison.  You are now dead.",
'foodpoisonedmsg':'User ate a poisoned %s',
'foodeaten':"That %s was very tasty!",
'drinkpoisoned':"That %s had a fatal poison inside.  You are now dead.",
'drinkpoisonedmdg':'User drank poison from a %s',
'playerdesc':'%s %s the %s %s, carrying %s, at %s, Level %s.  Can use the attacks %s',
'attackerror':'Not a valid attack.',
'itemhere':"There is a %s here",
'doorhere':"There is a door to the %s",
'doordesc':"A door to the %s that leads to the %s.",
'attack1':'Punch',
'attack1desc':'A simple punch',
'type1':'Normal',
'lang':'Language',
'iosask':'Are you on an iPhone or iPad?  This is important for gameplay.',
'iosquit':'User did not choose iPhone or iPad.'
}

import pickle

with open('english.lang', 'wb') as handle: pickle.dump(msgs, handle)
