msgs = {'title':"%s",
'title2':"%s - Versión %s",
'author':"Hecho por %s",
'version':"[green]Versión %s, [blue]Versión de Pelt %s",
'save1':"Guarda %s (no usado)",
'save2':"Guarda %s: %s",
'save3':"Guardar al archivo",
'save4':"Abrir archivo",
'savewarning':"[red]AVISO: Archivo era usada por %s %s el/la %s.  ¿Bien sobrescribir?",
'saveerror':"[red]Archivo no es valido.",
'colorerror':"[red]Entrada de color no es valido.",
'inputerror':"[red]Entrada no es valido",
'next':"Siguiente pagina",
'yes':"[green]Sí",
'no':"[red]No",
'quit':"[red]Quitar",
'back':"[red]Atrás",
'cancel':"[red]Cancelar",
'ok':"[green]Ok",
'open':"abre",
'closed':"cerrado",
'med':"Medio",
'fast':"Rapido",
'slow':"Lente",
'boy':"Niño",
'girl':"Niña",
'doormissing':"[red]No hay puerta en este direción.",
'doorlocked':"[red]Intenta abrir la puerta pero no se mueve.",
'directionerror':"[red]No es direción valido.",
'itemerror':"[red]No veo %s aquí.",
'cmderror':"[red]No se como hacer.",
'with':"con",
'using':"usando",
'usingerror':"¿Que quieres %s el/la %s con?",
'itemnormal':"Este %s no parece raro.",
'chestdescopen': "Una cofre que tiene %s y es abre.",
'chestdescclosed':"Una cofre cierra.",
'chestopenerror':"[red]¡La cofre es abre!",
'chestopen':"[blue]Opened the chest, %s was inside.", # <<< Continue Here
'chestunlocked':"[blue]Unlocked the chest using %s.",
'chestlocked':"[red]Chest is locked with a key.",
'foodpoisoned':"[red]That %s was covered in fatal poison.  You are now dead.",
'foodpoisonedmsg':"User ate a poisoned %s",
'foodeaten':"That %s was very tasty!",
'drinkpoisoned':"[red]That %s had a fatal poison inside.  You are now dead.",
'drinkpoisonedmsg':"User drank poison from a %s",
'playerdesc':"%s %s the %s %s, carrying %s, at %s, Level %s.  Can use the attacks %s",
'attackerror':"[red]Not a valid attack.",
'itemhere':"[yellow]There is a %s here",
'doorhere':"[yellow]There is a door to the %s",
'doordesc':"[yellow]A door to the %s that leads to the %s.",
'attack1':"Punch",
'attack1desc':"A simple punch",
'type1':"Normal",
'lang':"Language (Translations are not 100% accurate)",
'quitmsg':"Quit on user's demand.",
'iosask':"Are you on an iPhone or iPad?  This is important for gameplay.",
'iosquit':"User did not choose iPhone or iPad.",
'gamestart':"You are in a room.",
'gameaction':"What will you do?",
'gameinputerror':"I didn't understand what you typed.",
'helpquit':"quit - Saves and quits the game.",
'quitcmd':"quit",
'savecmd':"save",
'helpsave':"save - Saves the game",
'loadcmd':"load",
'helpload':"load - Loads the game from a save file (dangerous)",
'helpcmd':"help",
'helphelp':"help - Displays this message",
'examinecmd':"examine",
'helpexamine':"examine <item> - shows description of item",
'eatcmd':"eat",
'helpeat':"eat <item> - If item is food, will eat item",
'drinkcmd':"drink",
'helpdrink':"drink <item> - if item is a drink, will drink item",
'takecmd':"take",
'helptake':"take <item> - if item is movable, will take item",
'gocmd':"go",
'helpgo':"go <direction> - Go through the door in the defined direction",
'opencmd':"open",
'describecmd':"describe",
'helpdescribe':"describe - Tells what you see around you",
'problem':"¡Dios mío!  Hay una problema con el juego."
}

import pickle, os.path

rootdir = os.path.dirname(os.path.dirname(__file__))
resourcedir = os.path.join(rootdir, 'resources')
langsdir = os.path.join(resourcedir, 'langs')
langdir = os.path.join(langsdir, 'es')

def compile():
	with open(os.path.join(langdir, "es-pelt.lang"), 'wb') as handle: pickle.dump(msgs, handle)

compile()