msgs = {'title':u'Fur',
'author':u'Creado por Dark Tailed',
'version':u'Versión %s',
'title2':u'Fur - Versión %s',
'save1':u'Archivo %s',
'save2':u'Archivo %s: %s',
'save3':u'Guardar al Archivo',
'save4':u'Cargar al Archivo',
'savewarning':u'ATENCION: Archivo en uso de %s %s el/la %s.  ¿Bien para sobrescribir?',
'saveerror':u'Archivo no valido',
'colorerror':u'Color no valido',
'inputerror':u'Entrada no valida',
'nofriendnameerror':u"¡No entra el nombre de tu amigo!  Recuerda, %s es un(a) %s.",
'mailto1':u'mailto:dark.tailed.wolf@gmail.com?subject=I%20just%20played%20your%20game%20Fur!&body=I%20rate%20Fur%20(out%20of%205):%20',
'mailto2':u'Gracias por jugar a Fur!  Por favor envie sus comentarios pulsando en mi.',
'next':u'Siguiente Pagina',
'yes':u'Si',
'no':u'No',
'quit':u'Quitar',
'back':u'Atras',
'cancel':u'Cancelar',
'ok':u'Ok',
'open':u'abierto',
'closed':u'cerrado',
'med':u'Medio',
'fast':u'Rapido',
'slow':u'Lento',
'boy':u'Niño',
'girl':u'Niña',
'he':u'el',
'she':u'ella',
'her':u'ella',
'him':u'el',
'his':u'ello',
'meyou':u"tú y yo",
'you':u"tu",
'wolf':u"Lobo",
'cat':u"Gato",
'dragon':u"Dragón",
'bear':u"Oso",
'fox':u"Zorro",
'mouse':u"Ratón",
'bird':u"Pájaro",
'otter':u"Nutria",
'broken1':u'Hay algunas partes del juego que no funcionan por el momento.  Las partes se corregirán en breve.  Para cerrar estas alertas, haz clic en el "%s".',
'broken2':u'No Funciona',
'broken3':u"¡No funciona!",
'broken4':u"La siguiente parte esta todavia en desarrollo.  Carga un archivo del Beta Tester ahora para desbloquear la siguiente parte.",
'start':u'Comienza el Juego',
'load':u'Cargar al Archivo (No Funciona)',
'options':u'Opciones',
'scroll':u'Velocidad de Desplazamiento (%s)',
'annoy':u'Modo de Molestia (No Funciona)',
'beta':u'Modo de Beta Tester',
'annoyon':u"Modo de molestia esta activado.",
'betaon':u"Modo de beta tester esta activado.",
'annoyoff':u"Modo de molestia esta desactivado.",
'betaoff':u"Modo de beta tester esta desactivado.",
'quitmsg':u"Salí del juego en la demanda del usuario.",
'setupgndr':u'Eres un niño o una niña?',
'setuprace':u"Haz clic en un animal.",
'setupname':u'Tu nombre es?',
'setuplast':u'%s...y tu apellido?',
'setupeyeclose':u'%s %s...Bueno.  Ahora puede entrar por las puertas y encontrarte en "Fur"...cierra los ojos y cuenta hasta tres, y despues abre los ojos...',
'setupeyeopen':u"Deberias abrir tus ojos ahora.  Bueno.  Esto completa tu renacimiento.  Entraras Quilar como medio/a-%s...",
'p1m1':u'???: ...',
'p1m2':u'???: ...Oye...',
'p1m3':u'???: ...Despierta...',
'p1m4':u'???: ...¡Oye, %s perezoso!',
'p1m5':u'???: ¡Despierta!',
'p1m6':u'Lentamente abre tus ojos.  Un(a) %s de tu edad esta tratando de sacudir para despertarte.  Se nota algo extraño del/de la %s, pero sus ojos aun estan borrosos al despertar.',
'p1m7':u"???: ¡Estas despierto/a!  ¡Te sacudo por una hora ó mas!", # continue translating VVV
'p1m8':u"Your eyes focus and you figure out why the %s looked so strange.  %s was fox-like, with fur covering %s entire body, and a big tail sticking out behind %s.",
'p1m9':u"Your eyes widen and you quickly push yourself back into the wall.  You then raise your arms ready to attack.",
'p1m10':u'You: Who are you?',
'p1m11':u"???: Me?  My name is...",
'setup9':u'Enter the name of your friend, remember, %s is a %s.',
'p1m12':u"%s.  What's yours?",
'p1m13':u"You lower your fists.",
'p1m14':u"You: ...I'm %s.",
'p1m15':u"%s: %s...it's a funny name for a %s like %s!",
'p1m16':u"You: What?",
'p1m17':u"You then look down at yourself.  %s",
'foxdesc':u"You also look just like a fox, with a tail and everything.",
'dragondesc':u"You have scales and the tail of a dragon.  In your throat you feel a hot presence.",
'p1m18':u"They are in a similar state to those of the %s's.  %s",
'birddesc':u"However you have feathers down your arms like wings and a retrice.  You feel your face and find a bird's beak for your mouth.",
'wolfdesc':u"However you look more like a wolf with a wolf's tail.  You feel your face and find a big snout.",
'catdesc':u"However your hands have very sharp claws and you look more like a cat.",
'beardesc':u"However you have big hands, big feet, and a short, stubby tail.  You have brown fur just like a bear.",
'mousedesc':u"However you have small hands, a skinny tail, and big ears, just like a mouse.",
'otterdesc':u"However your hands look more like an otter's.  You feel your face and find wet quills.  Behind you is a long tail.",
'p1m19':u"You start to panic inside.  You think 'what is going on?'",
'p1m20':u"%s: ...What?",
'p1m21':u"You tell yourself to calm down so you can figure out why you're half-%s.",
'p1m22':u"You: I'm a human though...",
'p1m23':u"You accidentally said the last part out loud.  You meant only to think it.",
'p1m24':u"%s: WHAT!  You can't be, you've got every aspect of a %s anthro...(%s comes close to you and sniffs you, then pulls back)...and you smell just like one too.",
'p1m25':u"You: Yeah, thanks.",
'p1m26':u"%s: I didn't mean it like that!",
'p1m27':u"You: I don't know what's going on, but we're going to have to find out.  Where are we?",
'p1title':u'PART 1: Prologue',
'gamestart':u"You are in a room.",
'gameaction':u"What will you do?",
'gameinputerror':u"I didn't understand what you typed.",
'helpquit':u'quit - Saves and quits the game.',
'quitmsg':u"Quit on user's demand.",
'quitcmd':u'quit',
'savecmd':u'save',
'helpsave':u'save - Saves the game',
'loadcmd':u'load',
'helpload':u'load - Loads the game from a save file (dangerous)',
'helpcmd':u'help',
'helphelp':u'help - Displays this message',
'examinecmd':u'examine',
'helpexamine':u'examine [item] - shows description of item',
'eatcmd':u'eat',
'helpeat':u'eat [item] - If item is food, will eat item',
'drinkcmd':u'drink',
'helpdrink':u'drink [item] - if item is a drink, will drink item',
'takecmd':u'take',
'helptake':u'take [item] - if item is movable, will take item',
'gocmd':u'go',
'helpgo':u'go [direction] - Go through the door in the defined direction',
'doormissing':u"There is no door in that direction.",
'doorlocked':u"You try to open the door but the handle won't budge.",
'directionerror':u"That's not a proper direction.",
'itemerror':u"I don't see any %s here.",
'cmderror':u"I don't know how to do that.",
'with':u'with',
'using':u'using',
'usingerror':u"What do you want to %s the %s with?",
'itemnormal':u"This %s doesn't seem to be unusual.",
'chestdescopen':u"A chest that contains %s and is open.",
'chestdescclosed':u'A closed chest.',
'chestdescopen':u"A chest that contains %s and is %s.",
'chestdescclosed':u'A closed chest.',
'foodpoisoned':u"That %s was covered in fatal poison.  You are now dead.",
'foodpoisonedmsg':u'User ate a poisoned %s',
'foodeaten':u"That %s was very tasty!",
'drinkpoisoned':u"That %s had a fatal poison inside.  You are now dead.",
'drinkpoisonedmdg':u'User drank poison from a %s',
'playerdesc':u'%s %s the %s %s, carrying %s, at %s, Level %s.  Can use the attacks %s',
'attackerror':u'Not a valid attack.',
'itemhere':u"There is a %s here",
'doorhere':u"There is a door to the %s",
'doordesc':u"A door to the %s that leads to the %s.",
'attack1':u'Punch',
'attack1desc':u'A simple punch',
'type1':u'Normal',
'lang':u'Language',
'iosask':u'Are you on an iPhone or iPad?  This is important for gameplay.',
'iosquit':u'User did not choose iPhone or iPad.'
}

import pickle

with open('../spanish.lang', 'wb') as handle: pickle.dump(msgs, handle)
