msgs = ['Fur',
'Hecho de Dark Tailed',
'Version ADDON',
"Fur - Version ADDON",
"Pagina Proxima",
'Guarda ADDON',
'Guarda ADDON: ADDON',
'Guardar al Archivo',
'Cargar Archivo',
'AVISO: Archivo pertenece al ADDON ADDON el/la ADDON.  Esta bien para sobrescribir?',
'Archivo del guardar esta invalido,',
'Entrada de color no es valida.',
'mailto:dark.tailed.wolf@gmail.com?subject=Acabo%20de%20jugar%20su%20juego%20Fur!&body=Me%20clasificar%20Fur%20(de%205):%20',
'Gracias por jugar Fur! Por favor envie sus comentarios pulsando en mi.',
'Si',
'No',
'Quitar',
'Atras',
'Cancelar',
'Ok',
'Medio',
'Rapido',
'Lento',
'Chico',
"chico",
"ello",
'Chica',
"chica",
"ella",
"usted y yo",
"usted",
"Lobo",
"Gato",
"Dragon",
"Oso",
"Zorro",
"Raton",
"Pajaro",
"Nutria",
'Hay algunas partes del juego que se rompe en el momento. Las partes se corregiran en breve. Para cerrar estas alertas emergentes, presione "ADDON"',
'Broken ATM', #Continue translating from here
'Start Game',
'Load Game (ADDON)',
'Options',
'Scroll Speed (ADDON)',
'Annoyance Mode (ADDON)',
'Beta Tester Mode',
"Annoyance mode ADDON",
"Beta tester mode ADDON",
"now active.",
"revoked.",
"It's broken at the moment!",
"Next part is still in development.  Please load in a developer save to unlock the next part.",
"Quit on user's demand.",
'Not a valid choice.',
'Are you a boy or a girl?',
"Invalid input.",
'Your name is?',
'ADDON...and your last?',
"I can't hear what you are saying.",
'ADDON ADDON...Good.  Now you may enter the gates and find yourself in "Fur"...close your eyes and count to 3, then open your eyes...',
"You should've opened your eyes by now.  Good.  You have finished the first part of your rebirth.",
"The final part of your rebirth is to know what animal you would be if you couldn't be human anymore.",
"Choose an animal",
"You have chosen a ADDON.  Excellent...This concludes the second part of your rebirth.  You will enter Quilar as a half-ADDON...",
'???: ...',
'???: ...Hey...',
'???: ...Wake up...',
'???: ...Hey, you lazy ADDON!',
'???: Wake up!',
'You slowly open your eyes.  A young ADDON about your age is trying to shake you awake.  You notice something strange about the ADDON, but your eyes are still blurred from waking up.',
"???: You're awake!  I've been shaking you for over an hour or so!",
"You're eyes focus and you figure out why the ADDON looked so strange.  ADDON was fox-like, with fur covering ADDON entire body, and a big tail sticking out behind ADDON.",
"Your eyes widen and you quickly push yourself back into the wall.  You then raise your arms ready to attack.",
'You: Who are you?',
"???: Me?  My name is...",
'Enter the name of your friend, remember, ADDON is a ADDON.',
"ADDON.  What's yours?",
"You lower your fists.",
"You: ...I'm ADDON.",
"ADDON: ADDON...it's a funny name for a ADDON like ADDON!",
"You: What?",
"You then look down at yourself.  ADDON",
"You also look just like a fox, with a tail and everything.",
"You have scales and the tail of a dragon instead of the fur like a fox.",
"They are in a similar state to those of the ADDON's.  ADDON",
"However you have feathers down your arms like wings and a retrice.  You feel your face and find a bird's beak for your mouth.",
"However you look more like a wolf with a wolf's tail.  You feel your face and find a big snout.",
"However your hands have very sharp claws and you look more like a cat.",
"However you have big hands, big feet, and a short, stubby tail.  You have brown fur just like a bear.",
"However you have small hands, a skinny tail, and big ears, just like a mouse.",
"However your hands look more like an otter's.",
"You start to panic inside.  You think 'what is going on?'",
"ADDON: ...What?",
"You tell yourself to calm down so you can figure out why you're half-ADDON.",
"You: I'm a human though...",
"You accidentally said the last part out loud.  You meant only to think it.",
"ADDON: WHAT!  You can't be, you've got every aspect of a ADDON anthro...(ADDON comes close to you and sniffs you, then pulls back)...and you smell, just like one too."
"You: Yeah, thanks.",
"ADDON: I didn't mean it like that!",
"You: I don't know what's going on, but we're going to have to find out.  Where are we?",
'PART 1: Prologue',
"Next part is still in development.  Please load in a developer save to unlock the next part.",
"You are in a room.",
"What will you do?",
"I didn't understand what you typed.",
'quit',
'quit - Saves and quits the game.',
"Quit on user's demand.",
'save',
'save - Saves the game',
'load',
'help',
'help - Displays this message',
'examine',
'examine [item] - shows description of item',
'eat',
'eat [item] - If item is food, will eat item',
'drink',
'drink [item] - if item is a drink, will drink item',
'take',
'go',
'go [direction] - Go through the door in the defined direction',
"There is no door in that direction.",
"You try to open the door but the handle won't budge.",
"That's not a proper direction.",
"I don't see any ADDON here.",
"I don't know how to do that.",
'with',
'using',
"What do you want to ADDON the ADDON with?",
"This ADDON doesn't seem to be unusual.",
"That ADDON was covered in fatal poison.  You are now dead.",
'User ate a poisoned ADDON',
"That ADDON was very tasty!",
"That ADDON had a fatal poison inside.  You are now dead.",
'User drank poison from a ADDON',
'ADDON ADDON the ADDON ADDON, carrying ADDON, at ADDON, Level ADDON.  Can use the attacks ADDON',
'Not a valid attack.',
"There is a ADDON here",
"There is a door to the ADDON",
"A door to the ADDON that leads to the ADDON.",
'Punch',
'A simple punch',
'Normal',
'Language',
'him',
'her',
'Are you on an iPhone or iPad?  This is important for gameplay.'
'User did  not choose iPhone or iPad.'
]

import pickle

with open('spanish.lang', 'wb') as handle: pickle.dump(msgs, handle)